### ISSUE TITLE
Failed to read JSON: missing field `default_post_listing_type`

### ISSUE THREAD

**Issue by hugmouse** [Nutomic/lemmyBB#1]
Im writing this issue just in case if someone stumbles across this error 👀 

**Error**: 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to read JSON: missing field `default_post_listing_type` at line 1 column 1119', src/main.rs:55:25
```

**Possible solution**: use Lemmy version `>=0.16.4`

Im not going to close this issue immediately just in case if this error have something to do with other things than Lemmy version.

**Comment by Nutomic** [comment]
Fixed, works now with Lemmy 0.16.4 by pulling it from git.
